name = "Black & Light 2"
license = "MIT"
licenselink = "https://github.com/NickolasHKraus/black-and-light-2/blob/master/LICENSE"
description = "A beautifully simple, high contrast, text-oriented theme for Hugo. Black & Light 2 is hyper-performant, JavaScript-free, and fully open-source!"
homepage = "https://github.com/NickolasHKraus/black-and-light-2"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Nickolas Kraus"
  homepage = "https://nickolaskraus.io"

[original]
  name = "David Hamp-Gonsalves"
  homepage = "https://davidhampgonsalves.com"
  repo = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
